name: Run Tests

on:
  push:
    branches:
      - main
      - dev*

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.4
        ports:
          - 6379:6379
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: '8.3'
          tools: composer:v2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr
#          php-extensions: 'json, dom, curl, libxml, mbstring'
#          nova-email: ${{ secrets.NOVA_EMAIL }}
#          nova-password: ${{ secrets.NOVA_PASSWORD }}

      - name: Install Project Dependencies
        run: composer install -q --no-interaction --no-progress

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: php artisan test --compact --coverage --min=75
#        run: php artisan test --compact
